### ISSUE TITLE
Shoppingmall name

### ISSUE THREAD

**Issue by SungbumAhn** [KAIST-IS521/TeamTwo#11]
How we do decide the name of shopping mall? Does anyone have some ideas?

**Comment by dinggul** [comment]
I'd like to make it similar as Steam.

Hmm... How about Staem ? :smile:

**Comment by mfaerevaag** [comment]
Or a flag store? Could be ironic as it's going to be used for a CTF?

Name could be "Flags 'R' Us" (like the toy shop toysrus.com)
