### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/TeamTwo#15]
I think we should agree on a convention for the build system. As the assignment specifies, there should be a toplevel `Makefile` with a default target building every sub project. So, if every sub project also has a make file (e.g. `flagUpdater/Makefile.flag`), with the same default target, the toplevel make file could look like:

```Makefile
all: foo bar

foo:
    make -C foo

bar:
    make -C bar
```

Where `foo` and `bar` are each sub-project, `webServer` etc.

This makes the top-level make file simple to handle and isolates all sub-project specific build stuff to their respective directory.  What do you guys think?

**Comment by dinggul** [comment]
Agree

I think there is no other possible option

**Comment by dinggul** [comment]
From ae1f13b13e45d0030f280a05e2763968499fa1e2,
I checked that `make` at top directory works well.

Top level Makefile invokes lower level of it.

Now, remaining parts is detailed configuration for each part

**Comment by dinggul** [comment]
Finished with project
