### ISSUE TITLE
[Backend] DBMS choice 

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/TeamTwo#18]
I implemented with MySQL for the rapid prototyping. 
But some guys said 'they are familiar with SQLite. 

So, we choose the DBMS. 
The issue will be like the followings. 

1) compatibility test with current version of SQL script 
2) Makefile for installing DBMS without any problem

**Comment by dinggul** [comment]
I think initial setting for web service should be simple.

In those point of view, sqlite is much suitable choice I think

**Comment by nohkwak** [comment]
Yes, you are right. 
I find that MySQL is impossible to be set up with the 'make'. 
For example, Administrator has to login with root for configuring and making our database and account. 
It will be almost impossible only to type 'make'.  

I will raise this issue in the class git (KAIST-IS521/2017-spring) , 
Because someone has to migrate the code and data, it will take two hours or more.

**Comment by dinggul** [comment]
FYI, it is possible to set root password for mysql with only `make` command

Read this: http://bradthemad.org/tech/notes/mysql_setup.php

**Comment by nohkwak** [comment]
But, secure setup needs the manual configuration still. ㅠ.ㅠ 
I think Makefile has to be written in parallel.
