### ISSUE TITLE
[Backend] Please change sql files to use easily

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/TeamTwo#29]
For final submission, 
We should make all processes (include initial settings) automatically.

I think current sql files are not suitable for that.
Please check:https://github.com/KAIST-IS521/TeamOne/blob/master/db/Makefile
and apply similar format for our environment.

**Comment by nohkwak** [comment]
Refer commit 1f991c6, adce9b0, 19bfc66

**Comment by dinggul** [comment]
It is not worked well
I will fix it

**Comment by dinggul** [comment]
This issue is resolved
Check cd2b187c68cc58c8b35014fa9d7900a4d3676ae8
