### ISSUE TITLE
[Backend] in products.js

### ISSUE THREAD

**Issue by mickan921** [KAIST-IS521/TeamTwo#30]
Whenever I try to buy items that calls "router.get('/purchase ..."
one of the errors are
```
express deprecated req.param(name): Use req.params, req.body, or req.query instead routes/product.js:82:26
express deprecated req.param(name): Use req.params, req.body, or req.query instead routes/product.js:83:27
```
I looked up what the errors mean and it said that we need to change this 
```
    var product_id = req.param('product-id');
    var product_num = req.param('product-num');
```
to
```
    var product_id = req.param.product-id;
    var product_num = req.param.product-num;
```
But when we change that, the code won't work anymore! :(

**Comment by nohkwak** [comment]
Actually, what you did is not the error, it is just warning....

It is recommended that you fix it slightly from the working version.


2017-05-21 2:36 GMT+09:00 Jungsuk Oh <notifications@github.com>:
