### ISSUE TITLE
[Bank Connection Script] output format 

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/TeamTwo#34]
Is it possible to change output format like following? 

print ID 
print PW 
-->  print ID, PW

**Comment by nohkwak** [comment]
If error occurs, can you print through stderr ?

**Comment by dinggul** [comment]
Which message do you want when an error occured?

**Comment by nohkwak** [comment]
Any message is ok...
I just check whether stderr is printed or not ....

2017-05-23 17:47 GMT+09:00 Minjoon Park <notifications@github.com>:

**Comment by dinggul** [comment]
Do you need non 0 return code for triggering error function?

**Comment by nohkwak** [comment]
I close because it is discussed off-line...
