### ISSUE TITLE
[Integrate] change front-end UI in cart page

### ISSUE THREAD

**Issue by nohkwak** [KAIST-IS521/TeamTwo#35]
Hide purchase button in cart page when there are no item in cart page.. 
Although server handles it, 
it makes user push and get the error message.

**Comment by dinggul** [comment]
It already implemented I think.
when there is no item at cart, server should return 0. but now server return 1

If server do that, client would work well

**Comment by nohkwak** [comment]
OK Good, I also commit b823251 for double checking in server-side...

2017-05-23 17:49 GMT+09:00 Minjoon Park <notifications@github.com>:
